version: '3.9'
services:
  web:
    build: web
    depends_on:
      - db
    volumes:
      - ./code/sqli-labs:/var/www/html
    #network_mode: container:wireguard2
    environment:
      MYSQL_ROOT_USER: ${MYSQL_ROOT_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_DBNAME: ${MYSQL_DBNAME}
      MYSQL_DBNAME1: ${MYSQL_DBNAME1}
    ports:
      - "8080:80"
    networks:
      - default

  db:
    platform: linux/x86_64
    image: mysql:5.7.6
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "8989:3306"
    networks:
      - default

networks:
  default:
    name: wgnet_1
    external: true