version: "3.6"

services:

  portainer:
    image: portainer/portainer-ce:latest
    ports:
      - "9443:9443"
    volumes:
      - ./portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  # vpn1 - external adapter for proxy-container
  wireguard1:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard1
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - SERVERURL=185.68.21.231
      - SERVERPORT=51821
      - PEERS=2
      - PEERDNS=auto #optional
      - INTERNAL_SUBNET=10.1.1.0 #optional
      - PERSISTENTKEEPALIVE_PEERS= #optional
      - LOG_CONFS=true #optional
    volumes:
      - ./config1:/config
      #- /lib/modules:/lib/modules #optional
    ports:
      - 51821:51821/udp
      - 8081:80
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped

  # container for peer1
  cont_1:
    build: .
    image: nginx:stable
    volumes:
      - ./data/cont_1.html:/usr/share/nginx/html/index.html
    container_name: cont_1
#    ports:
#      - "8081:80" # внешний <- внутренний
    restart: unless-stopped
    network_mode: service:wireguard1

  # vpn2 - external adapter for proxy-container
  wireguard2:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard2
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - SERVERURL=185.68.21.231
      - SERVERPORT=51821
      - PEERS=2
      - PEERDNS=auto #optional
      - INTERNAL_SUBNET=10.1.2.0 #optional
      - PERSISTENTKEEPALIVE_PEERS= #optional
      - LOG_CONFS=true #optional
    volumes:
      - ./config2:/config
      #- /lib/modules:/lib/modules #optional
    ports:
      - 51822:51822/udp
      - 8082:80
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped

  # container for peer2
  cont_2:
    build: .
    image: nginx:stable
    volumes:
      - ./data/cont_2.html:/usr/share/nginx/html/index.html
    container_name: cont_2
#    ports:
#      - "8081:80" # внешний <- внутренний
    restart: unless-stopped
    network_mode: service:wireguard2
